CREATE TABLE pfMember(
id	VARCHAR(20) NOT NULL PRIMARY KEY,
NAME VARCHAR(20) NOT NULL,
pwd VARCHAR(20) NOT NULL,
phone VARCHAR(11) NOT NULL,
gender CHAR(1) NOT NULL,
pd CHAR(1) NOT NULL,
content VARCHAR(1000) NOT NULL
);

SELECT * FROM pfMember;